import { z } from 'zod'

export const ForwardRuleQuerySchema = z.object({
  botId: z.string().uuid().optional(),
})

export const ForwardRuleParamsSchema = z.object({
  id: z.string().uuid(),
})

export const CreateForwardRuleSchema = z.object({
  botId: z.string().uuid(),
  sourceEntityId: z.string().uuid(),
  destinationEntityId: z.string().uuid(),
  name: z.string().min(1).max(100),
  scheduleMode: z.number().min(0).max(1).optional(),
  batchSize: z.number().min(1).max(100).optional(),
  postInterval: z.number().min(1).optional(),
  postIntervalUnit: z.number().min(0).max(4).optional(),
  deleteAfterEnabled: z.boolean().optional(),
  deleteInterval: z.number().min(1).optional(),
  deleteIntervalUnit: z.number().min(0).max(5).optional(),
  broadcastEnabled: z.boolean().optional(),
  broadcastMessage: z.string().max(4000).optional(),
  broadcastParseMode: z.enum(['HTML', 'Markdown', 'MarkdownV2']).optional(),
  broadcastDeleteAfter: z.boolean().optional(),
  broadcastDeleteInterval: z.number().min(1).optional(),
  broadcastDeleteUnit: z.number().min(0).max(5).optional(),
  startFromMessageId: z.number().optional(),
  endAtMessageId: z.number().optional(),
  shuffle: z.boolean().optional(),
  repeatWhenDone: z.boolean().optional(),
  forwardMedia: z.boolean().optional(),
  forwardText: z.boolean().optional(),
  forwardDocuments: z.boolean().optional(),
  forwardStickers: z.boolean().optional(),
  forwardPolls: z.boolean().optional(),
  removeLinks: z.boolean().optional(),
  addWatermark: z.string().max(500).optional(),
  includeKeywords: z.array(z.string()).optional(),
  excludeKeywords: z.array(z.string()).optional(),
})

export const UpdateForwardRuleSchema = z.object({
  name: z.string().min(1).max(100).optional(),
  isActive: z.boolean().optional(),
  scheduleMode: z.number().min(0).max(1).optional(),
  batchSize: z.number().min(1).max(100).optional(),
  postInterval: z.number().min(1).optional(),
  postIntervalUnit: z.number().min(0).max(4).optional(),
  deleteAfterEnabled: z.boolean().optional(),
  deleteInterval: z.number().min(1).nullable().optional(),
  deleteIntervalUnit: z.number().min(0).max(5).nullable().optional(),
  broadcastEnabled: z.boolean().optional(),
  broadcastMessage: z.string().max(4000).nullable().optional(),
  broadcastParseMode: z.enum(['HTML', 'Markdown', 'MarkdownV2']).nullable().optional(),
  broadcastDeleteAfter: z.boolean().optional(),
  broadcastDeleteInterval: z.number().min(1).nullable().optional(),
  broadcastDeleteUnit: z.number().min(0).max(5).nullable().optional(),
  startFromMessageId: z.number().nullable().optional(),
  endAtMessageId: z.number().nullable().optional(),
  shuffle: z.boolean().optional(),
  repeatWhenDone: z.boolean().optional(),
  forwardMedia: z.boolean().optional(),
  forwardText: z.boolean().optional(),
  forwardDocuments: z.boolean().optional(),
  forwardStickers: z.boolean().optional(),
  forwardPolls: z.boolean().optional(),
  removeLinks: z.boolean().optional(),
  addWatermark: z.string().max(500).nullable().optional(),
  includeKeywords: z.array(z.string()).optional(),
  excludeKeywords: z.array(z.string()).optional(),
})
