export enum AppErrorCode {
  // General
  UNKNOWN = 'UNKNOWN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  FORBIDDEN = 'FORBIDDEN',
  ACCOUNT_PENDING_APPROVAL = 'ACCOUNT_PENDING_APPROVAL',
  ACCOUNT_REJECTED = 'ACCOUNT_REJECTED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  
  // Telegram
  TELEGRAM_BOT_ERROR = 'TELEGRAM_BOT_ERROR',
  INVALID_INVITE_LINK = 'INVALID_INVITE_LINK',
  INVITE_EXPIRED = 'INVITE_EXPIRED',
  INVITE_LIMIT_REACHED = 'INVITE_LIMIT_REACHED',
}
